const standardWorksDB = [
  {
    id: 1,
    category: "Painting",
    translations: {
      en: "Painting",
      es: "Pintura",
      uk: "Фарбування",
      ru: "Покраска",
    },
    works: [
      {
        id: "1.1",
        workName: "Ceiling Painting",
        translations: {
          en: "Ceiling Painting",
          es: "Pintura de techo",
          uk: "Фарбування стелі",
          ru: "Покраска потолка",
        },
        unit: "m2",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 12,
      },
      {
        id: "1.2",
        workName: "Wall Painting",
        translations: {
          en: "Wall Painting",
          es: "Pintura de pared",
          uk: "Фарбування стін",
          ru: "Покраска стен",
        },
        unit: "m2",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 15,
      },
      {
        id: "1.3",
        workName: "Floor Painting",
        translations: {
          en: "Floor Painting",
          es: "Pintura del suelo",
          uk: "Фарбування підлоги",
          ru: "Покраска пола",
        },
        unit: "m2",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 12,
      },
      {
        id: "1.4",
        workName: "Roof Painting",
        translations: {
          en: "Roof Painting",
          es: "Pintura de techo",
          uk: "Фарбування стелі",
          ru: "Покраска потолка",
        },
        unit: "m2",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 10,
      },
    ],
  },
  {
    id: 2,
    category: "Carpentry",
    translations: {
      en: "Carpentry",
      es: "Carpintería",
      uk: "Столярні роботи",
      ru: "Столырные работы",
    },
    works: [
      {
        id: "2.1",
        workName: "Parquet Installation",
        translations: {
          en: "Parquet Installation",
          es: "Instalación de parquet",
          uk: "Встановлення паркету",
          ru: "Установка паркета",
        },
        unit: "m2",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 10,
      },
      {
        id: "2.2",
        workName: "Door Installation",
        translations: {
          en: "Door Installation",
          es: "Instalación de puertas",
          uk: "Встановлення дверей",
          ru: "Установка дверей",
        },
        unit: "hr",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 15,
      },
      {
        id: "2.3",
        workName: "Window Installation",
        translations: {
          en: "Window Installation",
          es: "Instalación de ventanas",
          uk: "Встановлення вікон",
          ru: "Установка окон",
        },
        unit: "hr",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 12,
      },
      {
        id: "2.4",
        workName: "Ceiling Installation",
        translations: {
          en: "Ceiling Installation",
          es: "Instalación de techo",
          uk: "Встановлення стелі",
          ru: "Установка потолка",
        },
        unit: "hr",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 8,
      },
    ],
  },
  {
    id: 3,
    category: "Plumbing",
    translations: {
      en: "Plumbing",
      es: "Plomería",
      uk: "Сантехніка",
      ru: "Сантехника",
    },
    works: [
      {
        id: "3.1",
        workName: "Pipe Installation",
        translations: {
          en: "Pipe Installation",
          es: "Instalación de tubos",
          uk: "Встановлення труб",
          ru: "Установка труб",
        },
        unit: "m",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 5,
      },
      {
        id: "3.2",
        workName: "Faucet Installation",
        translations: {
          en: "Faucet Installation",
          es: "Instalación de fuentes",
          uk: "Встановлення фонтанів",
          ru: "Установка фонтанов",
        },
        unit: "m",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 8,
      },
      {
        id: "3.3",
        workName: "Shower Installation",
        translations: {
          en: "Shower Installation",
          es: "Instalación de duchas",
          uk: "Встановлення душа",
          ru: "Установка душа",
        },
        unit: "m",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 12,
      },
    ],
  },
  {
    id: 4,
    category: "Electronics",
    translations: {
      en: "Electronics",
      es: "Electrónica",
      uk: "Електроніка",
      ru: "Электроника",
    },
    works: [
      {
        id: "4.1",
        workName: "TV Installation",
        translations: {
          en: "TV Installation",
          es: "Instalación de televisores",
          uk: "Встановлення телевізорів",
          ru: "Установка телевизоров",
        },
        unit: "hr",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 15,
      },
      {
        id: "4.2",
        workName: "Computer Installation",
        translations: {
          en: "Computer Installation",
          es: "Instalación de computadoras",
          uk: "Встановлення комп'ютерів",
          ru: "Установка компьютеров",
        },
        unit: "hr",
        formula: "a * U",
        quantity: 0,
        priceForUnit: 12,
      },
    ],
  },
];

export default standardWorksDB;
